[versions]
kotlin = "2.1.20"
kotlin-runitme = "1.9.0"
agp = "8.5.2"
publish = "0.34.0"

android-compileSdk = "36"
android-targetSdk = "36"
android-minSdk = "21"

junit = "4.13.2"
robolectric = "4.13"
androidJunit = "1.2.1"
androidTestCore = "1.5.0"
androidTestRunner = "1.5.2"
androidEspresso = "3.6.1"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-runitme" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "kotlin" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidTestRunner" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidEspresso" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-multiplatform-android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }


